export const COUNTRY_LIST = [
  { countryCode: '86', cnName: '中国', enName: 'China' },
  { countryCode: '1242', cnName: '巴哈马', enName: 'Bahamas' },
  { countryCode: '1246', cnName: '巴巴多斯', enName: 'Barbados' },
  { countryCode: '1264', cnName: '安圭拉', enName: 'Anguilla' },
  {
    countryCode: '1268',
    cnName: '安提瓜和巴布达',
    enName: 'Antigua and Barbuda',
  },
  {
    countryCode: '1284',
    cnName: '英属维尔京群岛',
    enName: 'British Virgin Islands',
  },
  {
    countryCode: '1340',
    cnName: '美属维尔京群岛',
    enName: 'U.S. Virgin Islands',
  },
  { countryCode: '1345', cnName: '开曼群岛', enName: 'Cayman Islands' },
  { countryCode: '1441', cnName: '百慕大', enName: 'Bermuda' },
  { countryCode: '1473', cnName: '格林纳达', enName: 'Grenada' },
  {
    countryCode: '1649',
    cnName: '特克斯和凯科斯群岛',
    enName: 'Turks and Caicos Islands',
  },
  { countryCode: '1664', cnName: '蒙特塞拉特', enName: 'Montserrat' },
  {
    countryCode: '1670',
    cnName: 'Northern Mariana Islands',
    enName: 'Northern Mariana Islands',
  },
  { countryCode: '1671', cnName: '关岛', enName: 'Guam' },
  { countryCode: '1684', cnName: 'American Samoa', enName: 'American Samoa' },
  { countryCode: '1758', cnName: '圣卢西亚', enName: 'Saint Lucia' },
  { countryCode: '1767', cnName: '多米尼克', enName: 'Dominica' },
  {
    countryCode: '1784',
    cnName: '圣文森特和格林纳丁斯',
    enName: 'Saint Vincent and the Grenadines',
  },
  {
    countryCode: '1868',
    cnName: '特立尼达和多巴哥',
    enName: 'Trinidad and Tobago',
  },
  {
    countryCode: '1869',
    cnName: '圣基茨和尼维斯',
    enName: 'Saint Kitts and Nevis',
  },
  { countryCode: '1876', cnName: '牙买加', enName: 'Jamaica' },
  { countryCode: '20', cnName: '埃及', enName: 'Egypt' },
  { countryCode: '212', cnName: '摩洛哥', enName: 'Morocco' },
  { countryCode: '213', cnName: '阿尔及利亚', enName: 'Algeria' },
  { countryCode: '216', cnName: '突尼斯', enName: 'Tunisia' },
  { countryCode: '218', cnName: '利比亚', enName: 'Libya' },
  { countryCode: '220', cnName: '冈比亚', enName: 'Gambia' },
  { countryCode: '221', cnName: '塞内加尔', enName: 'Senegal' },
  { countryCode: '222', cnName: '毛里塔尼亚', enName: 'Mauritania' },
  { countryCode: '223', cnName: '马里', enName: 'Mali' },
  { countryCode: '224', cnName: '几内亚', enName: 'Guinea' },
  { countryCode: '225', cnName: '科特迪瓦', enName: 'Ivory Coast' },
  { countryCode: '226', cnName: '布基纳法索', enName: 'Burkina Faso' },
  { countryCode: '227', cnName: '尼日尔', enName: 'Niger' },
  { countryCode: '228', cnName: '多哥', enName: 'Togo' },
  { countryCode: '229', cnName: '贝宁', enName: 'Benin' },
  { countryCode: '230', cnName: '毛里求斯', enName: 'Mauritius' },
  { countryCode: '231', cnName: '利比里亚', enName: 'Liberia' },
  { countryCode: '232', cnName: '塞拉利', enName: 'Sierra Leone' },
  { countryCode: '233', cnName: '加纳', enName: 'Ghana' },
  { countryCode: '234', cnName: '尼日利亚', enName: 'Nigeria' },
  { countryCode: '235', cnName: '乍得', enName: 'Chad' },
  { countryCode: '236', cnName: '中非', enName: 'Central African Republic' },
  { countryCode: '237', cnName: '喀麦隆', enName: 'Cameroon' },
  { countryCode: '238', cnName: '佛得角', enName: 'Cape Verde' },
  { countryCode: '240', cnName: '赤道几内亚', enName: 'Equatorial Guinea' },
  { countryCode: '241', cnName: '加蓬', enName: 'Gabon' },
  { countryCode: '242', cnName: '刚果（布）', enName: 'Republic of the Congo' },
  {
    countryCode: '243',
    cnName: '刚果（金）',
    enName: 'Democratic Republic of the Congo',
  },
  { countryCode: '244', cnName: '安哥拉', enName: 'Angola' },
  { countryCode: '248', cnName: '塞舌尔', enName: 'Seychelles' },
  { countryCode: '249', cnName: '苏丹', enName: 'Sudan' },
  { countryCode: '250', cnName: '卢旺达', enName: 'Rwanda' },
  { countryCode: '251', cnName: '埃塞俄比亚', enName: 'Ethiopia' },
  { countryCode: '252', cnName: '索马里', enName: 'Somalia' },
  { countryCode: '253', cnName: '吉布提', enName: 'Djibouti' },
  { countryCode: '254', cnName: '肯尼亚', enName: 'Kenya' },
  { countryCode: '255', cnName: '坦桑尼亚', enName: 'Tanzania' },
  { countryCode: '256', cnName: '乌干达', enName: 'Uganda' },
  { countryCode: '257', cnName: '布隆迪', enName: 'Burundi' },
  { countryCode: '258', cnName: '莫桑比克', enName: 'Mozambique' },
  { countryCode: '260', cnName: '赞比亚', enName: 'Zambia' },
  { countryCode: '261', cnName: '马达加斯加', enName: 'Madagascar' },
  { countryCode: '262', cnName: '留尼汪', enName: 'Réunion' },
  { countryCode: '263', cnName: '津巴布韦', enName: 'Zimbabwe' },
  { countryCode: '264', cnName: '纳米尼亚', enName: 'Namibia' },
  { countryCode: '265', cnName: '马拉维', enName: 'Malawi' },
  { countryCode: '266', cnName: '莱索托', enName: 'Lesotho' },
  { countryCode: '267', cnName: '博茨瓦纳', enName: 'Botswana' },
  { countryCode: '268', cnName: '斯威士兰', enName: 'Swaziland' },
  { countryCode: '269', cnName: '马约特', enName: 'Comoros' },
  { countryCode: '27', cnName: '南非', enName: 'South Africa' },
  { countryCode: '291', cnName: '厄立特里亚', enName: 'Eritrea' },
  { countryCode: '297', cnName: '阿鲁巴', enName: 'Aruba' },
  { countryCode: '298', cnName: '法罗群岛', enName: 'Faroe Islands' },
  { countryCode: '299', cnName: '格陵兰', enName: 'Greenland' },
  { countryCode: '30', cnName: '希腊', enName: 'Greece' },
  { countryCode: '31', cnName: '荷兰', enName: 'Netherlands' },
  { countryCode: '32', cnName: '比利时', enName: 'Belgium' },
  { countryCode: '33', cnName: '法国', enName: 'France' },
  { countryCode: '34', cnName: '西班牙', enName: 'Spain' },
  { countryCode: '350', cnName: '直布罗陀', enName: 'Gibraltar' },
  { countryCode: '351', cnName: '葡萄牙', enName: 'Portugal' },
  { countryCode: '352', cnName: '卢森堡', enName: 'Luxembourg' },
  { countryCode: '353', cnName: '爱尔兰', enName: 'Ireland' },
  { countryCode: '354', cnName: '冰岛', enName: 'Iceland' },
  { countryCode: '355', cnName: '阿尔巴尼亚', enName: 'Albania' },
  { countryCode: '356', cnName: '马耳他', enName: 'Malta' },
  { countryCode: '357', cnName: '塞浦路斯', enName: 'Cyprus' },
  { countryCode: '358', cnName: '芬兰', enName: 'Finland' },
  { countryCode: '359', cnName: '保加利亚', enName: 'Bulgaria' },
  { countryCode: '36', cnName: '匈牙利', enName: 'Hungary' },
  { countryCode: '370', cnName: '立陶宛', enName: 'Lithuania' },
  { countryCode: '371', cnName: '拉脱维亚', enName: 'Latvia' },
  { countryCode: '372', cnName: '爱沙尼亚', enName: 'Estonia' },
  { countryCode: '373', cnName: '摩尔多瓦', enName: 'Moldova' },
  { countryCode: '374', cnName: '亚美尼亚', enName: 'Armenia' },
  { countryCode: '375', cnName: '白俄罗斯', enName: 'Belarus' },
  { countryCode: '376', cnName: '安道尔', enName: 'Andorra' },
  { countryCode: '377', cnName: '摩纳哥', enName: 'Monaco' },
  { countryCode: '378', cnName: '圣马力诺', enName: 'San Marino' },
  { countryCode: '379', cnName: '梵蒂冈', enName: 'Vatican' },
  { countryCode: '380', cnName: '乌克兰', enName: 'Ukraine' },
  { countryCode: '381', cnName: '塞尔维亚和黑山', enName: 'Serbia' },
  { countryCode: '382', cnName: 'Montenegro', enName: 'Montenegro' },
  { countryCode: '385', cnName: '克罗地亚', enName: 'Croatia' },
  { countryCode: '386', cnName: '斯洛文尼亚', enName: 'Slovenia' },
  { countryCode: '387', cnName: '波黑', enName: 'Bosnia and Herzegovina' },
  { countryCode: '389', cnName: '前南马其顿', enName: 'Macedonia' },
  { countryCode: '39', cnName: '意大利', enName: 'Italy' },
  { countryCode: '40', cnName: '罗马尼亚', enName: 'Romania' },
  { countryCode: '41', cnName: '瑞士', enName: 'Switzerland' },
  { countryCode: '420', cnName: '捷克', enName: 'Czech Republic' },
  { countryCode: '421', cnName: '斯洛伐克', enName: 'Slovakia' },
  { countryCode: '423', cnName: '列支敦士登', enName: 'Liechtenstein' },
  { countryCode: '43', cnName: '奥地利', enName: 'Austria' },
  { countryCode: '44', cnName: '英国', enName: 'Jersey' },
  { countryCode: '45', cnName: '丹麦', enName: 'Denmark' },
  { countryCode: '46', cnName: '瑞典', enName: 'Sweden' },
  { countryCode: '47', cnName: '斯瓦尔巴岛和扬马延岛', enName: 'Norway' },
  { countryCode: '48', cnName: '波兰', enName: 'Poland' },
  { countryCode: '49', cnName: '德国', enName: 'Germany' },
  { countryCode: '501', cnName: '伯利兹', enName: 'Belize' },
  { countryCode: '503', cnName: '萨尔瓦多', enName: 'El Salvador' },
  { countryCode: '504', cnName: '洪都拉斯', enName: 'Honduras' },
  { countryCode: '505', cnName: '尼加拉瓜', enName: 'Nicaragua' },
  { countryCode: '506', cnName: '哥斯达黎加', enName: 'Costa Rica' },
  { countryCode: '507', cnName: '巴拿马', enName: 'Panama' },
  {
    countryCode: '508',
    cnName: '圣皮埃尔和密克隆',
    enName: 'Saint Pierre and Miquelon',
  },
  { countryCode: '509', cnName: '海地', enName: 'Haiti' },
  { countryCode: '590', cnName: '瓜德罗普', enName: 'Guadeloupe' },
  { countryCode: '592', cnName: '圭亚那', enName: 'Guyana' },
  { countryCode: '596', cnName: '马提尼克', enName: 'Martinique' },
  {
    countryCode: '61',
    cnName: '科科斯（基林）群岛',
    enName: 'Heard Island and McDonald Islands',
  },
  { countryCode: '65', cnName: '新加坡', enName: 'Singapore' },
  { countryCode: '673', cnName: '文莱', enName: 'Brunei' },
  { countryCode: '676', cnName: '汤加', enName: 'Tonga' },
  { countryCode: '679', cnName: '斐济', enName: 'Fiji' },
  { countryCode: '680', cnName: '帕劳', enName: 'Palau' },
  { countryCode: '681', cnName: '瓦利斯和富图纳', enName: 'Wallis and Futuna' },
  { countryCode: '685', cnName: '萨摩亚', enName: 'Samoa' },
  { countryCode: '687', cnName: '新喀里多尼亚', enName: 'New Caledonia' },
  { countryCode: '688', cnName: '图瓦卢', enName: 'Tuvalu' },
  { countryCode: '689', cnName: '法属波利尼西亚', enName: 'French Polynesia' },
  { countryCode: '691', cnName: '密克罗尼西亚', enName: 'Micronesia' },
  { countryCode: '692', cnName: '马绍尔群岛', enName: 'Marshall Islands' },
  { countryCode: '7', cnName: '俄罗斯', enName: 'Russia' },
  { countryCode: '850', cnName: '朝鲜', enName: 'North Korea' },
  { countryCode: '855', cnName: '柬埔寨', enName: 'Cambodia' },
  { countryCode: '856', cnName: '老挝', enName: 'Laos' },
  { countryCode: '880', cnName: '孟加拉国', enName: 'Bangladesh' },
  { countryCode: '90', cnName: '土耳其', enName: 'Turkey' },
  { countryCode: '91', cnName: '印度', enName: 'India' },
  { countryCode: '92', cnName: '巴基斯坦', enName: 'Pakistan' },
  { countryCode: '93', cnName: '阿富汗', enName: 'Afghanistan' },
  { countryCode: '94', cnName: '斯里兰卡', enName: 'Sri Lanka' },
  { countryCode: '960', cnName: '马尔代夫', enName: 'Maldives' },
  { countryCode: '961', cnName: '黎巴嫩', enName: 'Lebanon' },
  { countryCode: '962', cnName: '约旦', enName: 'Jordan' },
  { countryCode: '963', cnName: '叙利亚', enName: 'Syria' },
  { countryCode: '964', cnName: '伊拉克', enName: 'Iraq' },
  { countryCode: '965', cnName: '科威特', enName: 'Kuwait' },
  { countryCode: '966', cnName: '沙特阿拉伯', enName: 'Saudi Arabia' },
  { countryCode: '967', cnName: '也门', enName: 'Yemen' },
  { countryCode: '968', cnName: '阿曼', enName: 'Oman' },
  {
    countryCode: '971',
    cnName: '阿拉伯联合酋长国',
    enName: 'United Arab Emirates',
  },
  { countryCode: '972', cnName: '以色列', enName: 'Israel' },
  { countryCode: '973', cnName: '巴林', enName: 'Bahrain' },
  { countryCode: '974', cnName: '卡塔尔', enName: 'Qatar' },
  { countryCode: '975', cnName: '不丹', enName: 'Bhutan' },
  { countryCode: '976', cnName: '蒙古', enName: 'Mongolia' },
  { countryCode: '977', cnName: '尼泊尔', enName: 'Nepal' },
  { countryCode: '98', cnName: '伊朗', enName: 'Iran' },
  { countryCode: '992', cnName: '塔吉克斯坦', enName: 'Tajikistan' },
  { countryCode: '993', cnName: '土库曼斯坦', enName: 'Turkmenistan' },
  { countryCode: '994', cnName: '阿塞拜疆', enName: 'Azerbaijan' },
  { countryCode: '995', cnName: '格鲁吉亚', enName: 'Georgia' },
  { countryCode: '996', cnName: '吉尔吉斯斯坦', enName: 'Kyrgyzstan' },
  { countryCode: '998', cnName: '乌兹别克斯坦', enName: 'Uzbekistan' },
  { countryCode: '1', cnName: '美国', enName: 'United States' },
  { countryCode: '1787', cnName: '波多黎各', enName: 'Puerto Rico' },
  { countryCode: '1809', cnName: '多米尼加', enName: 'Dominica' },
  { countryCode: '1829', cnName: '多米尼加', enName: 'Dominica' },
  { countryCode: '1849', cnName: '多米尼加', enName: 'Dominica' },
  { countryCode: '502', cnName: '危地马拉', enName: 'Guatemala' },
  { countryCode: '51', cnName: '秘鲁', enName: 'Peru' },
  { countryCode: '52', cnName: '墨西哥', enName: 'Mexico' },
  { countryCode: '54', cnName: '阿根廷', enName: 'Argentina' },
  { countryCode: '55', cnName: '巴西', enName: 'Brazil' },
  { countryCode: '56', cnName: '智利', enName: 'Chile' },
  { countryCode: '57', cnName: '哥伦比亚', enName: 'Colombia' },
  { countryCode: '58', cnName: '委内瑞拉', enName: 'Venezuela' },
  { countryCode: '591', cnName: '玻利维亚', enName: 'Bolivia' },
  { countryCode: '593', cnName: '厄瓜多尔', enName: 'Ecuador' },
  { countryCode: '595', cnName: '巴拉圭', enName: 'Paraguay' },
  { countryCode: '597', cnName: '苏里南', enName: 'Suriname' },
  { countryCode: '598', cnName: '乌拉圭', enName: 'Uruguay' },
  { countryCode: '5999', cnName: '库腊索', enName: 'Curacao' },
  { countryCode: '60', cnName: '马来西亚', enName: 'Malaysia' },
  { countryCode: '62', cnName: '印度尼西亚', enName: 'Indonesia' },
  { countryCode: '63', cnName: '菲律宾', enName: 'Philippines' },
  { countryCode: '64', cnName: '新西兰', enName: 'New Zealand' },
  { countryCode: '66', cnName: '泰国', enName: 'Thailand' },
  { countryCode: '81', cnName: '日本', enName: 'Japan' },
  { countryCode: '82', cnName: '韩国', enName: 'South Korea' },
  { countryCode: '84', cnName: '越南', enName: 'Vietnam' },
  { countryCode: '852', cnName: '香港', enName: 'Hong Kong' },
  { countryCode: '853', cnName: '澳门', enName: 'Macao' },
  { countryCode: '886', cnName: '台湾', enName: 'Taiwan' },
  { countryCode: '95', cnName: '缅甸', enName: 'Myanmar [Burma]' },
];
export const PASSWORD_REGEXP =
  /^(?![a-z]{6,16}$)(?![A-Z]{6,16}$)(?!\d{6,16}$)(?![_]{6,16}$)[a-zA-Z\d_]{6,16}$/;
export const EMAIL_REGEXP =
  /^[\w.\-]+@(?:[a-z0-9]+(?:-[a-z0-9]+)*\.)+[a-z]{2,3}$/;
export const TELE_REGEXP = /^1\d{10}$/;
export const US_TELE_REGEXP = /^\d{6,16}$/;
export enum LOGIN_TABS {
  EMAIL = 'email',
  TELE = 'tele',
}
export const DEFAULT_ADMIN_ROLE_CODE = 'manager-1000';
export const DEFAULT_NORMAL_ROLE_CODE = 'normal-1000';
